[package]
description = "Rust-assembler implementation of big integers arithmetic"
homepage = "http://ethcore.io"
license = "GPL-3.0"
name = "bigint"
version = "0.1.0"
authors = ["Ethcore <admin@ethcore.io>"]
build = "build.rs"

[build-dependencies]
rustc_version = "0.1"

[dependencies]
rustc-serialize = "0.3"
serde = "0.7.0"
heapsize = "0.3"

[features]
x64asm_arithmetic=[]
rust_arithmetic=[]
